name: Import Intune Settings Catalog Policies
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: GraphApi
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true
        enable-AzPSSession: true
    - name: Install Microsoft.Graph.Authentication
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module "Microsoft.Graph.Authentication"
        Get-Module "Microsoft.Graph.Authentication" -ListAvailable
        Connect-MgGraph -Identity
        Invoke-MgGraphRequest -Uri '/beta/organization' | Select-Object -ExpandProperty value
    - name: Import Intune Settings Catalog Policies
      shell: pwsh
      run: |
        .\Import-IntuneSettingsCatalogPolicy.ps1 -Folder .\SettingsCatalog